apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx:latest
      volumeMounts:
        - name: azure-files
          mountPath: /data
  volumes:
    - name: azure-files
      persistentVolumeClaim:
        claimName: azure-pvc-files