{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    usage: fileshare-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  azureFile:
    secretName: {{ .Values.persistentVolume.azureFile.secretName }}
    shareName: {{ .Values.persistentVolume.azureFile.shareName }}
    readOnly: {{ .Values.persistentVolume.azureFile.readOnly }}
{{- end }}