apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-pvc-files
spec:
  storageClassName: azure-files-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi