apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-sc
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - mfsymlinks
  - nosharesock
  - actimeo=30
parameters:
  skuName: Standard_LRS
  location: eastus
  resourceGroup: 1-9983e5c6-playground-sandbox
  storageAccount: tfstatstorag